# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [89]:
import numpy as np
np.__version__

'2.0.2'

In [90]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [91]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [92]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [93]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [94]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [95]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [96]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[ 0.29957005, -0.72521688, -0.97989258],
        [ 0.47300538, -0.35166047,  0.16046459],
        [-0.38602125,  0.44688015,  1.17486147]]),
 array([[0.22533276, 0.52979728, 0.6392177 ],
        [0.47277015, 0.50982718, 0.57654942],
        [0.78325737, 0.2690899 , 0.00789082]]))

In [97]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.

import numpy as np
R = np.random.randn(5,5)
A = 0.5*(R + R.T)
B = 0.5*(R - R.T)
A, B

(array([[-0.43522843, -0.22338883,  0.24071694, -1.01604966, -1.05872675],
        [-0.22338883, -2.4940945 ,  0.30840529, -0.23784907, -0.52451527],
        [ 0.24071694,  0.30840529,  1.00314349, -0.55359689, -0.20179353],
        [-1.01604966, -0.23784907, -0.55359689, -1.48448094,  0.51177091],
        [-1.05872675, -0.52451527, -0.20179353,  0.51177091,  1.3849043 ]]),
 array([[ 0.        ,  1.3180412 ,  0.31921592, -1.10114659,  0.40075935],
        [-1.3180412 ,  0.        ,  1.10585987, -0.33310102, -1.10504044],
        [-0.31921592, -1.10585987,  0.        , -0.55148008, -1.38409026],
        [ 1.10114659,  0.33310102,  0.55148008,  0.        ,  0.5141645 ],
        [-0.40075935,  1.10504044,  1.38409026, -0.5141645 ,  0.        ]]))

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [98]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [99]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [100]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [101]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

import numpy as np
np.matmul?
np.dot?

`np.matmul` calculates a product of two matrices. Scalars are not allowed

`np.dot` is the dot product of two matrices. Scalars are allowed.

`@` effectively multiplies two matrices. Suited for use with larger matrices, while `np.dot` will typically siffice for smaller ones.

`*` multiplies the entries in two matrices, but not the matrices themselves. Provides a completely different result from the other three.

In [102]:
# Example

A = np.random.randn (5, 5)
B = np.random.randn (5, 5)

print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)
print(A * B)

[[-3.10489488e-03 -1.43050281e+00  9.76338729e-01 -2.77775035e+00
   9.92172996e-01]
 [ 1.37992412e-01 -9.81767117e-01  2.60357887e+00  2.25198612e-01
   2.55468969e-01]
 [ 3.53817251e-01 -1.57387532e+00  3.80196795e-01 -8.93085645e-01
   4.56301437e-01]
 [ 2.06711537e+00 -2.58771320e+00  1.76202214e+00 -2.24349183e+00
  -8.26546894e-01]
 [-3.20603948e+00  9.41575886e-01 -4.50907562e+00  1.96906163e+00
   2.16414123e+00]]
[[-3.10489488e-03 -1.43050281e+00  9.76338729e-01 -2.77775035e+00
   9.92172996e-01]
 [ 1.37992412e-01 -9.81767117e-01  2.60357887e+00  2.25198612e-01
   2.55468969e-01]
 [ 3.53817251e-01 -1.57387532e+00  3.80196795e-01 -8.93085645e-01
   4.56301437e-01]
 [ 2.06711537e+00 -2.58771320e+00  1.76202214e+00 -2.24349183e+00
  -8.26546894e-01]
 [-3.20603948e+00  9.41575886e-01 -4.50907562e+00  1.96906163e+00
   2.16414123e+00]]
[[-3.10489488e-03 -1.43050281e+00  9.76338729e-01 -2.77775035e+00
   9.92172996e-01]
 [ 1.37992412e-01 -9.81767117e-01  2.60357887e+00  2.25198612e-

## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [103]:
import math

In [104]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

173 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Vectorized version

In [105]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

12.2 ms ± 68.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [106]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

 "%%timeit is an IPython magic command used to measure the execution time of Python code. It runs the code multiple times and provides the mean and standard deviation of the execution time, which helps in getting a more accurate performance measurement by accounting for minor fluctuations in execution. It's particularly useful for comparing the performance of different code snippets or optimizations"

In [107]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

In [108]:
def energy(x, v, m = 0.5, k = 2):
  T = 0.5 * m * v ** 2
  U = 0.5 * k * x ** 2
  return T + U

t = np.linspace(0, 100, 10)
x = np.sin(t)
v = np.cos(t)
E = energy(x, v)
print(E)

[0.25       0.9900329  0.28933857 0.91344691 0.39910083 0.77634312
 0.55625802 0.60748667 0.72783767 0.44230462]


## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [109]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [110]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

The first entry in the first array of eigenvalues corresponds to the first column of eigenvectors, the second eigenvalue to the second column of eigenvectors, etc.

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [111]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [112]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [113]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [114]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.

k = 2450
K = np.array([[ k, -k],
              [-k,  k]])

vals, vecs = np.linalg.eigh(X)

U = vecs
print("U @ U.T")
print(U @ U.T)

print("U.T @ U")
print(U.T @ U)

U @ U.T
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
U.T @ U
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [115]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.

k = 2450
K = np.array([[ k, -k],
              [-k,  k]])
vals, U = np.linalg.eigh(K)

lamb = np.diag(vals)
U.T @ U == np.eye(2)

U.T @ K @ U

array([[ 3.94430453e-31,  6.65719202e-14],
       [-8.69285906e-14,  4.90000000e+03]])

In [116]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

k = 2450
K = np.array([[ k, -k],
              [-k,  k]])
vals, U = np.linalg.eigh(K)

print("Eigenvalues:", vals)
print("Eigenvectors (See columns):", U)
print()

omega = np.sqrt(vals)
print("Frequency:", omega)
print()

lamb = np.diag(vals)
lamb2 = U.T @ K @ U

print("Lambda", lamb)
print("U.T @ K @ U =", lamb2)
print()
print("Diagonalization:", np.allclose(lamb, lamb2))
print()

print("Mode 1:", U[:,0])
print("Mode 2:", U[:,1])

Eigenvalues: [   0. 4900.]
Eigenvectors (See columns): [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Frequency: [ 0. 70.]

Lambda [[   0.    0.]
 [   0. 4900.]]
U.T @ K @ U = [[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]

Diagonalization: True

Mode 1: [-0.70710678 -0.70710678]
Mode 2: [-0.70710678  0.70710678]
